name: Create Release Branches
on:
    workflow_dispatch:
        inputs:
            date1:
                description: 'First date'
                required: true
                default: $(date +'%Y-%m-%d')
            date2:
                description: 'Second date'
                required: true
                default: $(date +'%Y-%m-%d')

jobs:
    create-release-branches:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Git user
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"

            - name: Create release branches
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  DATE1=${{ github.event.inputs.date1 }}
                  DATE2=${{ github.event.inputs.date2 }}
                  BRANCH_NAME1="release/${DATE1}"
                  BRANCH_NAME2="release/${DATE2}"
                  git checkout main
                  git pull origin main
                  git checkout -b $BRANCH_NAME1
                  git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $BRANCH_NAME1
                  git checkout main
                  git checkout -b $BRANCH_NAME2
                  git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} $BRANCH_NAME2
