name: Salesforce SFDX Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    sfdx-tests:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/gambe94/sf_automation:1.0.3
            credentials:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            env:
                SF_TARGET_USERNAME: ${{ secrets.SF_TARGET_USERNAME }}
                SF_TARGET_CLIENT_ID: ${{ secrets.SF_TARGET_CLIENT_ID }}
                SF_TARGET_INSTANCE_URL: ${{ secrets.SF_TARGET_INSTANCE_URL }}
                SF_TARGET_JWT_KEY: ${{ secrets.SF_TARGET_JWT_KEY }}
            ports:
                - 80

        steps:
            -   name: Check for dockerenv file
                run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Pull Salesforce SFDX Docker Image
                run: sf --version

            -   name: Debug Environment Variables
                run: |
                    pwd 
                    echo "$SF_TARGET_USERNAME"
                    echo "$SF_TARGET_CLIENT_ID"
                    echo "$SF_TARGET_INSTANCE_URL"
                    echo "$SF_TARGET_JWT_KEY"

            -   name: List files in the repository
                run: las -la