name: Release Pipeline

on:
    pull_request:
        branches:
            - main  # Trigger on PR to main

jobs:
    # Step 1: Validate Staging Environment
    validate_staging:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate Staging
              run: |
                  echo "Running validation on staging..."
                  # Simulated validation logic
                  echo "Validation completed successfully!"

    # Step 2: Deploy to Staging Environment
    deploy_staging:
        needs: validate_staging
        if: success()  # Only run if validation was successful
        runs-on: ubuntu-latest
        environment:
            name: staging
            url: https://staging.example.com  # Add Staging URL for visibility

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Staging
              run: |
                  echo "Deploying to staging..."
                  # Simulated deployment logic
                  echo "Deployment to staging completed!"

    # Step 3: Validate Production
    validate_production:
        needs: deploy_staging
        if: success()  # Only run if staging deployment was successful
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Validate Production
              run: |
                  echo "Running validation against production..."
                  # Simulated validation logic
                  echo "Production validation completed successfully!"

    # Step 4: Deploy to Production
    deploy_production:
        needs: validate_production
        if: success()  # Only run if production validation was successful
        runs-on: ubuntu-latest
        environment:
            name: production
            url: https://production.example.com  # Add Production URL for visibility

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Production
              run: |
                  echo "Deploying to production..."
                  # Simulated deployment logic
                  echo "Deployment to production completed!"
